version: '3.9'

services:
  db-postgres:
    container_name: db-medpulse
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: med_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "med_db", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mobileapp_med_pulse_medservice-net
    restart: unless-stopped

  go-api:
    container_name: api-medPulse
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db-postgres:
        condition: service_healthy
    ports:
      - "65323:${APP_PORT:-8080}"  # Используем значение из .env или по умолчанию 8080
    env_file:
      - .env
    networks:
      - mobileapp_med_pulse_medservice-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mobileapp_med_pulse_medservice-net:
